# Generated by Django 6.1.2 on 2026-10-07 00:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name="Date d'émission")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('unpaid', 'Impayée'), ('paid', 'Payée')], default='unpaid', max_length=10)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='Total (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='InvoiceApp.client')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Produit')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='Prix unitaire (FCFA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='InvoiceApp.invoice')),
            ],
        ),
    ]
